### ISSUE TITLE
Exiting REPL with control-D

### ISSUE THREAD

**Issue by asgillett** [gwen-interpreter/gwen#31]
On linux, if I exit the REPL by typing control-D instead of "exit", then I get:
```
gwen>
INFO - Closing environment context
INFO - Closing browser session
java.lang.NullPointerException
	at gwen.eval.GwenREPL.eval(GwenREPL.scala:62)
	at gwen.eval.GwenREPL.run(GwenREPL.scala:114)
	at gwen.eval.GwenApp.$anonfun$run$2(GwenApp.scala:52)
	at gwen.eval.GwenApp.$anonfun$run$2$adapted(GwenApp.scala:52)
	at scala.Option.foreach(Option.scala:257)
	at gwen.eval.GwenApp.$anonfun$run$1(GwenApp.scala:52)
...
```

**Comment by bjuric** [comment]
Thanks @asgillett . This is done and released in gwen version [2.4.0](https://github.com/gwen-interpreter/gwen/releases/tag/v2.4.0). Close when ready.
